/* Generated by MyraPad at 20.06.2025 21:31:15 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace CellLight
{
	partial class EditorGUI: Panel
	{
		private void BuildUI()
		{
			FTPSlabel = new Label();
			FTPSlabel.Text = "FPS:/nTPS:";
			FTPSlabel.Id = "FTPSlabel";

			ContrastSlider = new HorizontalSlider();
			ContrastSlider.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			ContrastSlider.Maximum = 1;
			ContrastSlider.Width = 200;
			ContrastSlider.Height = 20;
			ContrastSlider.Border = new SolidBrush("#D9D9D9FF");
			ContrastSlider.BorderThickness = new Thickness(1, 0, 0, 1);
			ContrastSlider.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			ContrastSlider.Background = new SolidBrush("#212121FF");
			ContrastSlider.Id = "ContrastSlider";

			ContrastLabel = new Label();
			ContrastLabel.Text = "Contrast:";
			ContrastLabel.Top = -20;
			ContrastLabel.Width = 200;
			ContrastLabel.Height = 20;
			ContrastLabel.Border = new SolidBrush("#D9D9D9FF");
			ContrastLabel.BorderThickness = new Thickness(1, 0, 0, 0);
			ContrastLabel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			ContrastLabel.Background = new SolidBrush("#202020FF");
			ContrastLabel.Id = "ContrastLabel";

			Brush1 = new RadioButton();
			Brush1.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel1.png");
			Brush1.Width = 40;
			Brush1.Height = 40;
			Brush1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush1.Background = new SolidBrush("#000000FF");
			Brush1.Id = "Brush1";

			Brush2 = new RadioButton();
			Brush2.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel3.png");
			Brush2.Width = 40;
			Brush2.Height = 40;
			Brush2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush2.Background = new SolidBrush("#000000FF");
			Brush2.Id = "Brush2";

			Brush3 = new RadioButton();
			Brush3.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel5.png");
			Brush3.Width = 40;
			Brush3.Height = 40;
			Brush3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush3.Background = new SolidBrush("#000000FF");
			Brush3.Id = "Brush3";

			Brush4 = new RadioButton();
			Brush4.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel7.png");
			Brush4.Width = 40;
			Brush4.Height = 40;
			Brush4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush4.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush4.Background = new SolidBrush("#000000FF");
			Brush4.Id = "Brush4";

			Brush5 = new RadioButton();
			Brush5.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel9.png");
			Brush5.Width = 40;
			Brush5.Height = 40;
			Brush5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush5.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush5.Background = new SolidBrush("#000000FF");
			Brush5.Id = "Brush5";

			Brush6 = new RadioButton();
			Brush6.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel11.png");
			Brush6.Width = 40;
			Brush6.Height = 40;
			Brush6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush6.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush6.Background = new SolidBrush("#000000FF");
			Brush6.Id = "Brush6";

			Brush7 = new RadioButton();
			Brush7.UncheckedImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("PNGS/IconEditorPanel13.png");
			Brush7.Width = 40;
			Brush7.Height = 40;
			Brush7.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Brush7.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Brush7.Background = new SolidBrush("#000000FF");
			Brush7.Id = "Brush7";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.ShowGridLines = true;
			horizontalStackPanel1.GridLinesColor = ColorStorage.CreateColor(217, 217, 217, 255);
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalStackPanel1.Width = 280;
			horizontalStackPanel1.Height = 40;
			horizontalStackPanel1.Border = new SolidBrush("#D9D9D9FF");
			horizontalStackPanel1.BorderThickness = new Thickness(1, 1, 1, 0);
			horizontalStackPanel1.Widgets.Add(Brush1);
			horizontalStackPanel1.Widgets.Add(Brush2);
			horizontalStackPanel1.Widgets.Add(Brush3);
			horizontalStackPanel1.Widgets.Add(Brush4);
			horizontalStackPanel1.Widgets.Add(Brush5);
			horizontalStackPanel1.Widgets.Add(Brush6);
			horizontalStackPanel1.Widgets.Add(Brush7);

			Nvaluetxtbox = new TextBox();
			Nvaluetxtbox.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Nvaluetxtbox.Left = 190;
			Nvaluetxtbox.Width = 100;
			Nvaluetxtbox.Height = 20;
			Nvaluetxtbox.Border = new SolidBrush("#D9D9D9FF");
			Nvaluetxtbox.BorderThickness = new Thickness(1, 0, 0, 1);
			Nvaluetxtbox.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Nvaluetxtbox.Background = new SolidBrush("#202020FF");
			Nvaluetxtbox.Id = "Nvaluetxtbox";

			Nvaluelabel = new Label();
			Nvaluelabel.Text = "Refraction";
			Nvaluelabel.Left = 190;
			Nvaluelabel.Top = -20;
			Nvaluelabel.Width = 100;
			Nvaluelabel.Height = 20;
			Nvaluelabel.Border = new SolidBrush("#D9D9D9FF");
			Nvaluelabel.BorderThickness = new Thickness(1, 0, 0, 0);
			Nvaluelabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Nvaluelabel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Nvaluelabel.Background = new SolidBrush("#202020FF");
			Nvaluelabel.ClipToBounds = true;
			Nvaluelabel.Id = "Nvaluelabel";

			var label1 = new Label();
			label1.Text = "Cha/nnge";
			label1.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			label1.Width = 40;
			label1.Height = 40;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			Nvaluebtn = new Button();
			Nvaluebtn.Left = 260;
			Nvaluebtn.Width = 40;
			Nvaluebtn.Height = 40;
			Nvaluebtn.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Nvaluebtn.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Nvaluebtn.Id = "Nvaluebtn";
			Nvaluebtn.Content = label1;

			
			MinWidth = 1280;
			MaxWidth = 1920;
			MinHeight = 720;
			MaxHeight = 1080;
			ZIndex = 10;
			Widgets.Add(FTPSlabel);
			Widgets.Add(ContrastSlider);
			Widgets.Add(ContrastLabel);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(Nvaluetxtbox);
			Widgets.Add(Nvaluelabel);
			Widgets.Add(Nvaluebtn);
		}

		
		public Label FTPSlabel;
		public HorizontalSlider ContrastSlider;
		public Label ContrastLabel;
		public RadioButton Brush1;
		public RadioButton Brush2;
		public RadioButton Brush3;
		public RadioButton Brush4;
		public RadioButton Brush5;
		public RadioButton Brush6;
		public RadioButton Brush7;
		public TextBox Nvaluetxtbox;
		public Label Nvaluelabel;
		public Button Nvaluebtn;
	}
}
